experiment_name: 'rsna_slice_pe_resnext_101'
trial_name: 'pos_only'
phase: 'train'

lightning:
  trainer:
    gpus: '0'
    #distributed_backend: 'ddp'
    max_epochs: 1
    lr: 1e-4
    precision: 16
    auto_lr_find: false
    benchmark: true
    profiler: 'simple'
  checkpoint_callback:
    monitor: 'val_loss'
    dirpath: './data/ckpt'
    save_last: true
    mode: 'min'
    save_top_k: 1
  early_stopping_callback:
    monitor: 'val_loss'
    min_delta: 0.00
    patience: 5
    verbose: False
    mode: 'min'
  logger:
    logger_type: 'WandbLogger'
    save_dir: './data/logger/'
    name: 'pe_model_2d'
    project: 'pe_models'


model: 
  type: 'model_2d'
  model_name: 'resnext_101'
  freeze_cnn: false
  pretrained: true

data: 
  use_hdf5: false
  dataset: 'rsna'
  type: '2d'     # 1d, 2d, 3d, window 
  targets: 'rsna_pe_slice_target'
  channels: 'repeat'   # repeat, neighbor, window
  weighted_sample: true
  positive_only: true
  imsize: 512
    
transforms: 
  ShiftScaleRotate:
    shift_limit: 0.05
    scale_limit: 0.05
    rotate_limit: 20
    p: 1.0
  RandomCrop:
    height: 448
    width: 448
  RandomContrast:
    limit: 0.1
    p: 1.0
  
train: 
  batch_size: 30
  num_workers: 16
  weighted_loss: false
  loss_fn: 
    name: 'BCEWithLogitsLoss'
  optimizer: 
    name: 'Adam'
    weight_decay: 1e-6
  scheduler: 
    name: 'ReduceLROnPlateau'
    monitor: 'val_loss'
    interval: 'epoch'
    frequency: 3
    factor: 0.5
    patience: 5
