experiment_name: 'rsna_slice_pe'
trial_name: 'pos_only'
phase: 'train'
checkpoint: '/home/mschuang/pe_models_benchmark/data/ckpt/rsna_slice_pe_pos_only/1/2021_12_01_15_42_57/epoch=8-step=5561.ckpt'

lightning:
  trainer:
    gpus: '0'
    #distributed_backend: 'ddp'
    max_epochs: 30
    precision: 16
    lr: 0.0001
    auto_lr_find: true
    benchmark: true
    profiler: 'simple'
    #limit_train_batches: 0.1
    #val_check_interval: 0.25
  checkpoint_callback:
    monitor: 'val/mean_auroc'
    dirpath: './data/ckpt'
    save_last: true
    mode: 'max'
    save_top_k: 5
  early_stopping_callback:
    monitor: 'val/mean_auroc'
    min_delta: 0.00
    patience: 5
    verbose: False
    mode: 'max'
  logger:
    logger_type: 'WandbLogger'
    save_dir: './data/logger/'
    name: 'pe_model_2d'
    project: 'models_sweep'

model:
  type: 'model_2d'
  model_name: 'resnext_101'
  freeze_cnn: false
  pretrained: true

data:
  use_hdf5: false
  dataset: 'rsna'
  type: '2d'     # 1d, 2d, 3d, window
  targets: 'rsna_pe_slice_target'
  channels: 'window'   # repeat, neighbor, window
  weighted_sample: true
  positive_only: false
  imsize: 256
 
transforms:
  type: 'imagenet'
  ShiftScaleRotate:
    shift_limit: 0.05
    scale_limit: 0.05
    rotate_limit: 20
    p: 0.5
  RandomCrop:
    height: 224
    width: 224

train:
  batch_size: 64
  num_workers: 12
  weighted_loss: false
  loss_fn:
    name: 'BCEWithLogitsLoss'
  optimizer:
    name: 'Adam'
    weight_decay: 1e-6
  scheduler:
    name: 'ReduceLROnPlateau'
    monitor: 'val_loss'
    interval: 'epoch'
    frequency: 3
    factor: 0.5
    patience: 5
