program: run.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config"
  - "/home/mschuang/pe_models_benchmark/configs/supervised/pe_model_2d/config.yaml"
  - "--gpus"
  - "0"
  - "--train"
method: grid
metric:
  name: val/mean_auroc.best
  goal: maximize
parameters:
  model.model_name:
    distribution: categorical
    values:
      - 'resnet_101'
      - 'resnext_101'
      - 'efficientnet_b4'
      - 'vit_base_16'
  data.channels:
    distribution: categorical
    values:
      - 'repeat'
      - 'neighbor'
      - 'window'
