experiment_name: 'rsna_slice_pe_resnet_18_0.1'
trial_name: 'pos_only'
phase: 'train'
checkpoint: '/home/mschuang/pe_models_benchmark/data/ckpt/rsna_slice_pe_resnet_18_0.1_pos_only/1/2021_11_27_06_52_04/epoch=0-step=19465.ckpt'


lightning:
  trainer:
    gpus: 1
    #distributed_backend: 'ddp'
    max_epochs: 20
    lr: 0.001
    precision: 16
    auto_lr_find: false
    benchmark: true
    profiler: 'simple'
  checkpoint_callback:
    monitor: 'val/mean_auroc'
    dirpath: './data/ckpt'
    save_last: true
    mode: 'max'
    save_top_k: 5
  early_stopping_callback:
    monitor: 'val/mean_auroc'
    min_delta: 0.00
    patience: 5
    verbose: False
    mode: 'max'
  logger:
    logger_type: 'WandbLogger'
    save_dir: './data/logger/'
    name: 'pe_model_2d'
    project: 'pe_models'


model: 
  type: 'model_2d'
  model_name: 'resnet_18'
  freeze_cnn: false
  pretrained: true

data: 
  use_hdf5: false
  dataset: 'rsna'
  type: '2d'     # 1d, 2d, 3d, window 
  targets: 'rsna_pe_slice_target'
  channels: 'window'   # repeat, neighbor, window
  weighted_sample: true
  positive_only: false
  imsize: 256
    
transforms: 
  type: 'imagenet'
  ShiftScaleRotate:
    shift_limit: 0.05
    scale_limit: 0.05
    rotate_limit: 20
    p: 0.5
  RandomCrop:
    height: 224
    width: 224
  
train: 
  batch_size: 64
  num_workers: 12
  weighted_loss: false
  loss_fn: 
    name: 'BCEWithLogitsLoss'
  optimizer: 
    name: 'Adam'
    weight_decay: 1e-6
  scheduler: 
    name: 'ReduceLROnPlateau'
    monitor: 'val_loss'
    interval: 'epoch'
    frequency: 3
    factor: 0.5
    patience: 5
