program: run.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config"
  - "./configs/supervised/pe_model_2d/resnet18/exp001.yaml"
  - "--gpus" 
  - "0"
  - "--train"
method: bayes
metric:
  name: val/mean_auroc.best
  goal: maximize
parameters:
  lightning.trainer.lr:
    distribution: categorical
    values:
      - 0.001
      - 0.0001
  data.channels:
    distribution: categorical
    values:
      - 'repeat'
      - 'neighbor'
      - 'window'
  data.positive_only:
    distribution: categorical
    values:
      - true
      - false
