program: run.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config"
  - "/home/mschuang/pe_models_benchmark/configs/supervised/pe_model_1d/config.yaml"
  - "--gpus"
  - "0"
  - "--train"
method: bayes
metric:
  name: val/mean_auroc.best
  goal: maximize
parameters:
  model.aggregation:
    distribution: categorical
    values:
      - 'max'
      - 'mean'
      - 'attention'
  model.seq_encoder.rnn_type:
    distribution: categorical
    values:
      - 'LSTM'
      - 'GRU'
  model.seq_encoder.hidden_size:
    distribution: categorical
    values:
      - 64
      - 128
      - 256
  model.seq_encoder.bidirectional:
    distribution: categorical
    values:
      - true
      - false
  model.seq_encoder.num_layers:
    distribution: categorical
    values:
      - 1
      - 3 
      - 5
  model.seq_encoder.dropout_prob:
    distribution: categorical
    values:
      - 0.0
      - 0.25
      - 0.5
      - 0.75
  data.num_slices:
    distribution: categorical
    values:
      - 150
      - 200
      - 250
      - 300
  data.sample_strategy:
    distribution: categorical
    values:
      - 'fix'
      - 'random'
