program: run.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config"
  - "./configs/supervised/pe_model_window/coclr/exp002.yaml"
  - "--gpus" 
  - "0"
  - "--train"
method: bayes
metric:
  name: val/auroc.best
  goal: maximize
parameters:
  lightning.trainer.lr:
    distribution: log_uniform 
    min: -9.2
    max: -2.3
    # distribution: uniform 
    # min: 0.0001
    # max: 0.1
    # distribution: categorical
    # values:
    #   - 0.1
    #   - 0.01
    #   - 0.001
    #   - 0.0001